# Generated by Django 5.0.3 on 2024-05-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.IntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='menu_images/')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api_app.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('metode', models.CharField(max_length=50)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='api_app.pesanan')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_menu', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_app.pesanan')),
            ],
        ),
    ]
