# Generated by Django 5.0.3 on 2024-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='metode',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash')], max_length=50),
        ),
    ]
