# Generated by Django 5.0.3 on 2024-05-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_pembayaran_nomor_wa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='nomor_wa',
            new_name='nomor_hp',
        ),
    ]
