# Generated by Django 5.0.3 on 2024-07-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_rename_nomor_wa_pembayaran_nomor_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('proses', 'prosess'), ('selesai', 'selesai')], default='pending', max_length=20),
        ),
    ]
