# Generated by Django 5.0.3 on 2024-07-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_pesanan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tersedia',
            field=models.BooleanField(default=True),
        ),
    ]
