# Generated by Django 5.0.3 on 2024-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_menu_tersedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='status',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(choices=[('proses', 'prosess'), ('selesai', 'selesai')], default='pending', max_length=20),
        ),
    ]
