# Generated by Django 5.0.3 on 2024-07-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_remove_pesanan_status_pembayaran_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(choices=[('proses', 'Proses'), ('selesai', 'Selesai')], default='proses', max_length=20),
        ),
    ]
